version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_processos
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT

volumes:
  postgres_data: 