version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_clientes
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=123456
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=20.206.149.115
      - DB_PORT=5432

volumes:
  postgres_data: 